from swift_types import *

@swift_object
class Email:
    
    def set_cc_recipients(self, recipients: list[str]):...

    def set_bcc_recipients(self, recipients: list[str]):...

    def set_to_recipients(self, recipients: list[str]):...



    def set_body(self, body: str, html: bool):...

    def set_subject(self, subject: str):...

    def set_title(self, title: str):...

    def add_attachment(self, image_data: bytes, filename: str):...
    
    def send(self): ...
