from swift_types import *

@swift_object
class SMS:

    def add_recipients(self, recipients: list[str]):...

    def add_body(self, body: str):...

    def add_subject(self, subject: str):...

    def add_title(self, title: str):...

    def add_attachment(self, image_data: bytes, filename: str):...
    
    def send(self): ...
