from swift_types import *

@wrapper
class Notification:
    
    def new_notification(self, title: str, message: str, timing: float, id: str, should_repeate: bool): ...

    def remove_notification(self, id: str): ...

    def increase_badge_count(self, count: int): ...

    def reset_bagde_count(self): ...